package com.accolite.bitmagic;

/*
 Given an array arr[] of N positive elements. 
 The task is to find the Maximum AND Value generated by 
 any pair(arri, arrj) from the array such that i != j.
Note: AND is bitwise '&' operator.
 */
public class _Problem12_MaximumANDValue_TODO {
	public static void main(String[] args) {
		int N=4;
		int[] arr= {4,8,12,16};
		int value=maxAND(arr,N);
		System.out.println(value);
	}

	private static int maxAND(int[] arr, int n) {
		// TODO Auto-generated method stub
		return 0;
	}

}
